// src/routes/values/+page.svelte
<script>
</script>

<svelte:head>
  <title>Values</title>
  <meta name="description" content="What I care most about"/>
</svelte:head>

<section>
  <div class="more">
    <h1 class="more-hero-headline">Defining Principals</h1>
    <div class="more-details">
      <div class="principal">
        <h3>Ownership</h3>
        <p>Taking full responsibility for delivering success.</p>
      </div>
      <div class="principal">
        <h3>Collaboration</h3>
        <p>
          The value produced by an effective team exceeds the efforts of an
          MVP.
        </p>
      </div>
      <div class="principal">
        <h3>Unbound Potential</h3>
        <p>
          There is nothing that cannot be overcome. <br/>
          Surpass the status quo; challenge complacency.
        </p>
      </div>
      <div class="principal">
        <h3>Essentialism</h3>
        <p>Focus on bringing great meaning to a small set of goals.</p>
      </div>
      <div class="principal">
        <h3>Recovery</h3>
        <p>Growth is fostered by effective rest.</p>
      </div>
    </div>
  </div>
</section>


<style>
  .more-hero-headline {
    font-size: 3rem;
    margin-top: 2rem;
    font-weight: 300;
    color: #fff;
  }

  h3 {
    margin-bottom: 0;
  }

  .principal {
    margin-bottom: 2.5rem;
  }

  .more {
    margin: auto;
    max-width: 550px;
  }

  .more-details {
    line-height: 1.5rem;
  }
</style>

// src/views/Values.vue
<template>
  <Layout>
    <div class="more">
      <h1 class="more-hero-headline">Defining Principals</h1>
      <div class="more-details">
        <div class="principal">
          <h3>Ownership</h3>
          <p>Taking full responsibility for delivering success.</p>
        </div>
        <div class="principal">
          <h3>Collaboration</h3>
          <p>
            The value produced by an effective team exceeds the efforts of an
            MVP.
          </p>
        </div>
        <div class="principal">
          <h3>Unbound Potential</h3>
          <p>
            There is nothing that cannot be overcome. <br />
            Surpass the status quo; challenge complacency.
          </p>
        </div>
        <div class="principal">
          <h3>Essentialism</h3>
          <p>Focus on bringing great meaning to a small set of goals.</p>
        </div>
        <div class="principal">
          <h3>Recovery</h3>
          <p>Growth is fostered by effective rest.</p>
        </div>
      </div>
    </div>
  </Layout>
</template>

<style lang="scss">
.more-hero-headline {
  font-size: 3rem;
  margin-top: 2rem;
  font-weight: 300;
  color: #fff;
}

h3 {
  margin-bottom: 0rem;
}

.principal {
  margin-bottom: 2.5rem;
}

.social-links {
  margin: 2rem 0;
  display: flex;
  justify-content: space-evenly;
}

.social-button {
  max-height: 100px;
}

.dashboardLink {
  font-size: 1.5rem;
  text-decoration: none;
  color: #e8ad4f;
  word-break: break-all;
}

.more {
  margin: auto;
  max-width: 550px;
}

.more-details {
  line-height: 1.5rem;
}
</style>

<script>
import Layout from "../components/Layout";
export default {
  name: "Home",
  components: { Layout },
};
</script>
